server:
  port: 8003
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8003/eureka
  server:
    eviction-interval-timer-in-ms: 10000